If you're looking to integrate with Sendlane or are interested in our
partnership, affiliate, or agency program opportunities, we have three
different options available!

* *Integration Partner*: Choose this option if you have a SaaS solution
that you would like to integrate with Sendlane
* *Affiliate Partner*: If you would like to promote Sendlane to
audiences like content creators, eCommerce brands, or SaaS Applications
choose this option
* *Agency Partner*: If you'd like to use Sendlane to help your clients
increase their ROI with data-driven marketing automation, become an
agency partner

To become a partner, click through to visit our
https://www.sendlane.com/partner[Partner Center]. 

Then, choose the partnership option that you're interested in and enter
your information. Our partnership manager will review the details and
reach out to you with the next steps!

If you have any questions about our partnership programs, please email
us at partners@sendlane.com

'''''

=== Additional Resources

* https://www.sendlane.com/blog-posts/is-sendlane-affiliate-marketing-friendly[Is
Sendlane Affiliate Marketing Friendly?]
* https://www.sendlane.com/blog-posts/email-marketing-dos-donts[Email
Marketing Do's and Don'ts]
