[[top]]
==== Overview

You can specify up to nine colors to be displayed prominently anywhere
color pickers appear in Sendlane, including the email builder, form
builder, and reviews. Read on to learn how to set brand colors and
fonts!

[[account-wide]]
===== ⚠️ Brand colors are set for the entire account

If you have multiple stores under one Sendlane account, you will set
brand colors for all brands on your Account > Branding page.

==== In this guide

* link:#set-color[Set preferred colors]
* link:#remove-color[Remove a color or color palette]

'''''

[[set-color]]
=== Set preferred colors

To set preferred colors:

. Click the *Account* icon
. Click *Branding*
. Click *+ Create Palette*
. Click the *circle icon* to select a preferred color
. Click the *dots icon* and drag the colors to rearrange them
. Click *Add* to add a new color
. Click *Save* to save your preferred colors

image:https://lh7-us.googleusercontent.com/docsz/AD_4nXdxxzjxjJ4vfjMLWFYuuwZxqByeS-McgZpxRcYP90xTamlgU_jpG6lNmJf2bbc_nmsO09bMtKRSahp5phMM0W783B7xuHPBNE_YbYm3m0COx57C9j95fQPmnVeVvWepUMRuaIaw5C0JqT_YH7zPODKeJgGN?key=g9E22OxugrKaa8noqRTA9g[https://lh7-us.googleusercontent.com/docsz/AD_4nXdxxzjxjJ4vfjMLWFYuuwZxqByeS-McgZpxRcYP90xTamlgU_jpG6lNmJf2bbc_nmsO09bMtKRSahp5phMM0W783B7xuHPBNE_YbYm3m0COx57C9j95fQPmnVeVvWepUMRuaIaw5C0JqT_YH7zPODKeJgGN?key=g9E22OxugrKaa8noqRTA9g,width=1680,height=929]

[[remove-color]]
=== Remove a color or color palette

You can remove one color from your color palette or delete your entire
color palette and start over.

To remove a color from your color palette:

. In the color palette, click the *edit* icon
. Next to the color you want to delete, click the *trash can* icon
. Click *Delete*
. Click *Save*

image:https://lh7-us.googleusercontent.com/docsz/AD_4nXcy_hKMhHORy660cEQi8T95frAnl71X8hx8CO_nDuTmWOZdBOvRsDeUfb31cTr0qLXea_Td1y8acXkfVXK_8vVUoIhWjY5Q5pKmuIQGQ6Kacx36izrn_3BJFk5daegSYBA1QytwT__d7QBahtXoepYc5CP0?key=g9E22OxugrKaa8noqRTA9g[https://lh7-us.googleusercontent.com/docsz/AD_4nXcy_hKMhHORy660cEQi8T95frAnl71X8hx8CO_nDuTmWOZdBOvRsDeUfb31cTr0qLXea_Td1y8acXkfVXK_8vVUoIhWjY5Q5pKmuIQGQ6Kacx36izrn_3BJFk5daegSYBA1QytwT__d7QBahtXoepYc5CP0?key=g9E22OxugrKaa8noqRTA9g,width=1680,height=1049]

To delete your entire color palette:

. In the color palette, click the *trash can* icon
. Click *Delete*

image:https://lh7-us.googleusercontent.com/docsz/AD_4nXcY4DwdXjVLf2j8ltmSLvBDgJGSFQ3KFOoGjEOIGUk9V8kUrkD1zWl0pZIkzJ75BD1PIQNLwjNLOjuHybx1dbprwiSikVDFgbWyBsK__bVbpFRdhdVAonRZcBHot8di7k91Kj0y7Xnard0m-aGTwJOgtgag?key=g9E22OxugrKaa8noqRTA9g[https://lh7-us.googleusercontent.com/docsz/AD_4nXcY4DwdXjVLf2j8ltmSLvBDgJGSFQ3KFOoGjEOIGUk9V8kUrkD1zWl0pZIkzJ75BD1PIQNLwjNLOjuHybx1dbprwiSikVDFgbWyBsK__bVbpFRdhdVAonRZcBHot8di7k91Kj0y7Xnard0m-aGTwJOgtgag?key=g9E22OxugrKaa8noqRTA9g,width=1680,height=1049]
