Two-factor authentication (2FA) helps to protect your Sendlane account.
We recommend using two-factor authentication to keep your account as
secure as possible!

2FA is set at the user level, not the account level.

=== Set Up Two-Factor Authentication

When you log in to Sendlane, you'll see a screen with a QR code. Scan
this QR code with an authentication app like Google Authenticator,
Authy, or Microsoft Authenticator.

Once you connect your authenticator app, you'll see a six-digit
verification code to use in the next step.

Click *Next*, enter the verification code, then click *Next* to finish
logging in.

Your account is now secured with two-factor authentication! You will be
prompted again in 30 days to re-authenticate your account.

=== FAQ

====== How do I remove two-factor authentication after it's been set up?

Account owners can request to turn off two-factor authentication for
themselves or any other user in their account from their Customer
Success Manager or our 24/7 Product Support team. If you are not an
account owner, please have your account owner request 2FA removal.

Please include the following information in your request to remove 2FA
for a user in your account:

* The names of two Lists in your account
* The names of two Segments in your account
* A picture of your driver's license or other official identification

====== I never want to turn on 2FA; how can I permanently skip the prompts to turn it on?

2FA is highly recommended to keep your account secure. There is no way
to skip the 2FA prompts permanently.

====== I didn't receive a verification code!

Review the documentation for the authenticator app you used or reach out
to your authenticator app's support for next steps:

* https://support.google.com/accounts/answer/1066447?hl=en&co=GENIE.Platform%3DAndroid[Google
Authenticator]
* https://support.authy.com/hc/en-us/articles/115001945848-Downloading-and-Installing-Authy-Apps[Authy]
* https://www.microsoft.com/en-us/security/mobile-authenticator-app[Microsoft
Authenticator]
