==== Overview

Most modern internet browsers support Sendlane. Read on to learn more
about accessing Sendlane.

==== In this guide

* link:#supported[Supported browsers]
* link:#mobile[Mobile functionality]
* link:#troubleshooting[Troubleshooting]

'''''

[[supported]]
=== Supported browsers

You can use any of the following browsers to access Sendlane, but we
highly recommend Chrome for the best experience:

* Chrome
* Firefox
* Safari
* Opera Edge

[[mobile]]
=== Mobile functionality

You can access Sendlane from your mobile device, but Sendlane is not
optimized for mobile viewing or functionality. For the best experience,
access Sendlane on your desktop browser.

=== Troubleshooting

If you are having trouble loading Sendlane in a supported browser,
ensure your browser is up to date. See instructions below for
determining whether you need to update your browser:

* https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DDesktop[Chrome]
* https://support.mozilla.org/en-US/kb/update-firefox-latest-release[Firefox]
* https://support.apple.com/en-us/102665[Safari]
* https://help.opera.com/en/latest/crashes-and-issues/[Opera]
* https://support.microsoft.com/en-us/topic/microsoft-edge-update-settings-af8aaca2-1b69-4870-94fe-18822dbb7ef1[Edge]
