:last-update-label:
[#top]
= How to adjust attribution settings
:page-title: How to adjust attribution settings  // Default page title, modify per article
:page-aliases:  // Add aliases as /path/to/old/url
:page-status: draft  // Options: draft, in-review, published, deprecated
:page-description:  // Optimize for SEO
:author: Author Name
:keywords: keyword1, keyword2
:page-diataxis:  // Options: explanation (explaining a concept not guiding users through a process), how-to (guiding users through a process with a prescriptive outcome), reference, tutorial (teaches users a new concept)

// Article content starts here
[#abstract]
[abstract]
--
This article explains how to adjust attribution settings.
For detailed information about attribution, see How Sendlane attributes revenue.
--

[#intro]
== Introduction

Attribution window settings can be adjusted on the settings page to match attribution settings in previous providers or changing marketing strategies.

Check out https://help.sendlane.com/article/542-how-sendlane-attributes-revenue-to-email-and-sms[How Sendlane calculates attribution] for an overview of Sendlane’s attribution defaults and best practices before adjusting your own attribution settings.


[#adjust]
== Adjust attribution options

[#considerations]
==== Considerations to make before changing attribution settings

* Adjusted attribution settings will be applied to reporting only for messages sent or Contact actions taken after the changes are made.
For example, if you adjust attribution settings and later a Contact engages with a campaign sent before changes were made and makes a purchase that meet new attribution qualifications, that conversion will be applied to the older Campaign.
Purchases made before the attribution settings were adjusted that qualify for the new attribution settings will not be retroactively applied to Campaign reporting.
* Automation attribution will not reset when attribution settings are updated.
Revenue attribution for Automation message nodes will continue to sum cumulatively when attribution settings are adjusted.
* Attribution settings are applied to Campaigns and Automations as soon as you click Save Changes.

Users who have moved to Sendlane from another platform should adjust attribution to match the settings used in the previous platform for continuity.

If you're not sure what your previous attribution settings were, check out the help docs below from popular providers on their default attribution settings and where to look for customized settings:

[cols=",,",]
|===
|Attentive
|link:++https://help.attentivemobile.com/hc/en-us/articles/7050482152212-FAQs-Attentive-s-attribution-model#what-types-of-conversions-does-attentive-support--0-0++[Default
Settings]
|link:++https://help.attentivemobile.com/hc/en-us/articles/7050482152212-FAQs-Attentive-s-attribution-model#can-i-customize-the-attentive-attribution-window--0-2++[Customized
Settings]

|Postscript
|https://help.postscript.io/hc/en-us/articles/4402883425051-Customize-Your-Attribution-Windows#What-is-an-Attribution-Window?[Default
Settings]
|https://help.postscript.io/hc/en-us/articles/4402883425051-Customize-Your-Attribution-Windows#Adjust-Your-Attribution-Windows[Customized
Settings]

|Klaviyo
|https://help.klaviyo.com/hc/en-us/articles/1260804504250[Default
Settings]
|https://help.klaviyo.com/hc/en-us/articles/11118357030555[Customized
Settings]
|===

To adjust attribution settings:

. Click the *Account* icon
. Click *Attribution*
. Select attribution settings and windows
. Click *Save Changes*

link:#top[Back to top]

[#converted]
== View contacts who converted

Use the Conversion tab in Campaign and Automation email reports to see Contacts that have an attributed conversion for the Campaign or Automation email:

image:https://lh7-us.googleusercontent.com/_JZ2nQDsKxtn8R4-L8-pEvBrl2lkQgg8xxaM_ZvvrNJkINeiZ9q7nhb1P3JsBrDEpptkD_1ZVOU_JR5lRP_tl8RZeFEvxwPKR-y78zmbWDSr3flc5oo0bYIk4epzcRhs9oZD5ghe7D-iIBDrQ28ISWY[https://lh7-us.googleusercontent.com/_JZ2nQDsKxtn8R4-L8-pEvBrl2lkQgg8xxaM_ZvvrNJkINeiZ9q7nhb1P3JsBrDEpptkD_1ZVOU_JR5lRP_tl8RZeFEvxwPKR-y78zmbWDSr3flc5oo0bYIk4epzcRhs9oZD5ghe7D-iIBDrQ28ISWY,width=720,height=444]

link:#top[Back to top]
